name: poo
version: '1.0'
main: dev.navickasm.poo.Poo
api-version: '1.21'
authors: [ 'Mack Navickas' ]
description: 'Spawns poo when player crouches; toggleables'

commands:
  poo:
    description: Operates the poo plugin.
    usage: /poo <toggle|chance [value%]|despawn [seconds]|cooldown [seconds]>

permissions:
  poo.toggle:
    description: Allows toggling the Poo plugin.
    default: op
  poo.chance:
    description: Allows setting the chance for poo to drop.
    default: op
  poo.despawn:
    description: Allows setting despawn time of the poo.
    default: op